#!/usr/bin/env python3
"""Build the anti-hallucination layer: INDEX.md (human) + manifest.json (machine)
from everything fetch.py has collected in <dest>/.sdr/fetched.json.

The downstream project agent should treat manifest.json as ground truth:
every claim it makes should be traceable to a local_path listed here.

Usage:
  python3 manifest.py --dest ~/research/llm-training \
      --topic "local LLM training" --effort high [--stats round-stats.json]
"""
from __future__ import annotations
import argparse
import json
from datetime import datetime
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dest", required=True)
    ap.add_argument("--topic", default="")
    ap.add_argument("--effort", default="")
    ap.add_argument("--stats", default=None,
                    help="optional JSON with budget stats {rounds, duration_min, saturated, novelty_last}")
    args = ap.parse_args()

    dest = Path(args.dest).expanduser()
    fetched_file = dest / ".sdr" / "fetched.json"
    state_file = dest / ".sdr" / "state.json"
    items = json.loads(fetched_file.read_text()) if fetched_file.exists() else []
    state = json.loads(state_file.read_text()) if state_file.exists() else {}
    stats = json.loads(Path(args.stats).read_text()) if args.stats else {}

    manifest = {
        "topic": args.topic,
        "effort": args.effort,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "generator": "scientific-deep-research",
        "volume_used_mb": round(state.get("bytes_used", 0) / 1024 / 1024, 1),
        "budget_stats": stats,
        "document_count": len(items),
        "documents": [
            {k: it.get(k) for k in (
                "id", "type", "title", "authors", "year", "date", "venue",
                "citations", "score", "doi", "url", "query",
                "local_path", "size_bytes", "abstract")}
            for it in items
        ],
    }
    (dest / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False))

    by_query: dict[str, list] = {}
    for it in items:
        by_query.setdefault(it.get("query") or "misc", []).append(it)

    lines = [
        f"# Research Index — {args.topic or dest.name}",
        "",
        f"Generated by [scientific-deep-research](https://github.com/legifx/scientific-deep-research)"
        f" on {datetime.now():%Y-%m-%d %H:%M} · effort: **{args.effort or 'n/a'}**"
        f" · {len(items)} documents · {manifest['volume_used_mb']} MB",
        "",
    ]
    if stats:
        sat = "saturated (topic exhausted)" if stats.get("saturated") else "NOT saturated — more exists at higher effort"
        lines += [
            f"> Budget: {stats.get('rounds', '?')} rounds, ~{stats.get('duration_min', '?')} min, "
            f"final novelty rate {stats.get('novelty_last', '?')} — {sat}",
            "",
        ]
    lines += [
        "All documents below exist locally. Downstream agents: cite by `local_path`,",
        "do not invent sources beyond this list (see `manifest.json`).",
        "",
    ]
    for query, group in sorted(by_query.items()):
        lines.append(f"## {query}")
        lines.append("")
        for it in sorted(group, key=lambda x: -(x.get("score") or 0)):
            authors = ", ".join((it.get("authors") or [])[:3])
            if len(it.get("authors") or []) > 3:
                authors += " et al."
            cit = it.get("citations")
            meta = " · ".join(filter(None, [
                str(it.get("year") or ""),
                it.get("venue") or "",
                f"{cit} citations/stars" if cit is not None else None,
                f"score {it.get('score')}",
            ]))
            loc = it.get("local_path")
            lines.append(f"- **{it['title']}** — {authors}")
            lines.append(f"  {meta}")
            lines.append(f"  [source]({it.get('url')})"
                         + (f" · local: `{loc}`" if loc and loc != "<link-only>" else " · *link only (not downloaded)*"))
            abstract = (it.get("abstract") or "")[:220]
            if abstract:
                lines.append(f"  > {abstract}{'…' if len(it.get('abstract') or '') > 220 else ''}")
            lines.append("")
    (dest / "INDEX.md").write_text("\n".join(lines))
    print(f"wrote {dest / 'INDEX.md'} and {dest / 'manifest.json'} ({len(items)} documents)")


if __name__ == "__main__":
    main()
