#!/usr/bin/env python3
"""Build the anti-hallucination layer: INDEX.md (human) + manifest.json (machine)
from everything fetch.py has collected in <dest>/.sdr/fetched.json.

The downstream project agent should treat manifest.json as ground truth:
every claim it makes should be traceable to a local_path listed here.

Documents carry a `status`:
  downloaded      a local file exists and was verified where possible
  link_only       the download failed; the reason is in `failure_reason`
  pdf_unverified  a file exists but its text does not match the title

`schema_version` lets downstream agents tell which shape they are reading.

Usage:
  python3 manifest.py --dest ~/research/llm-training \
      --topic "local LLM training" --effort high [--stats round-stats.json]
"""
from __future__ import annotations
import argparse
import json
from datetime import datetime
from pathlib import Path

SCHEMA_VERSION = 2

DOC_FIELDS = (
    "id", "type", "title", "authors", "year", "date", "venue",
    "citations", "score", "legacy_score", "relevance", "doi", "url", "query",
    "local_path", "size_bytes", "abstract", "status", "failure_reason",
    "conflict", "conflict_fields", "conflict_detail", "title_match",
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dest", required=True)
    ap.add_argument("--topic", default="")
    ap.add_argument("--effort", default="")
    ap.add_argument("--stats", default=None,
                    help="optional JSON with budget stats {rounds, duration_min, saturated, novelty_last}")
    args = ap.parse_args()

    dest = Path(args.dest).expanduser()
    fetched_file = dest / ".sdr" / "fetched.json"
    state_file = dest / ".sdr" / "state.json"
    items = json.loads(fetched_file.read_text()) if fetched_file.exists() else []
    state = json.loads(state_file.read_text()) if state_file.exists() else {}
    stats = json.loads(Path(args.stats).read_text()) if args.stats else {}
    report = common_report(dest)

    docs = []
    for it in items:
        d = {k: it.get(k) for k in DOC_FIELDS}
        d["status"] = it.get("status") or ("downloaded" if it.get("local_path") else "link_only")
        docs.append(d)

    conflicts = sum(1 for d in docs if d.get("conflict"))
    link_only = sum(1 for d in docs if d["status"] == "link_only")
    unverified = sum(1 for d in docs if d["status"] == "pdf_unverified")
    rel = [d.get("relevance") for d in docs if isinstance(d.get("relevance"), (int, float))]

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "topic": args.topic,
        "effort": args.effort,
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "generator": "scientific-deep-research",
        "volume_used_mb": round(state.get("bytes_used", 0) / 1024 / 1024, 1),
        "volume_unit": "disk_blocks",
        "budget_stats": stats,
        "document_count": len(docs),
        "report": {
            **report,
            "conflicts": conflicts,
            "link_only": link_only,
            "pdf_unverified": unverified,
            "mean_relevance": round(sum(rel) / len(rel), 3) if rel else None,
        },
        "documents": docs,
    }
    (dest / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False))

    by_query: dict = {}
    for d in docs:
        by_query.setdefault(d.get("query") or "misc", []).append(d)

    lines = [
        f"# Research Index — {args.topic or dest.name}",
        "",
        f"Generated by [scientific-deep-research](https://github.com/legifx/scientific-deep-research)"
        f" on {datetime.now():%Y-%m-%d %H:%M} · effort: **{args.effort or 'n/a'}**"
        f" · {len(docs)} documents · {manifest['volume_used_mb']} MB",
        "",
    ]
    if conflicts or link_only or unverified:
        flags = []
        if conflicts:
            flags.append(f"**{conflicts} metadata conflicts** — sources disagree; see `conflict_detail`")
        if link_only:
            flags.append(f"{link_only} link-only entries — download failed, reason in `failure_reason`")
        if unverified:
            flags.append(f"{unverified} PDFs unverified — content does not match the title")
        lines += ["> " + " · ".join(flags), ""]
    if stats:
        sat = "saturated (topic exhausted)" if stats.get("saturated") else "NOT saturated — more exists at higher effort"
        lines += [
            f"> Budget: {stats.get('rounds', '?')} rounds, ~{stats.get('duration_min', '?')} min, "
            f"final novelty rate {stats.get('novelty_last', '?')} — {sat}",
            "",
        ]
    lines += [
        "Downstream agents: cite by `local_path`, do not invent sources beyond",
        "this list. Documents without a `local_path` were not downloaded —",
        "they may be mentioned, but not cited as read sources.",
        "",
    ]
    for query, group in sorted(by_query.items()):
        lines.append(f"## {query}")
        lines.append("")
        for it in sorted(group, key=lambda x: -(x.get("score") or 0)):
            authors = ", ".join((it.get("authors") or [])[:3])
            if len(it.get("authors") or []) > 3:
                authors += " et al."
            cit = it.get("citations")
            meta = " · ".join(filter(None, [
                str(it.get("year") or ""),
                it.get("venue") or "",
                f"{cit} citations/stars" if cit is not None else None,
                f"score {it.get('score')}",
                f"relevance {it['relevance']}" if it.get("relevance") is not None else None,
            ]))
            loc = it.get("local_path")
            lines.append(f"- **{it['title']}** — {authors}")
            lines.append(f"  {meta}")
            if loc:
                tail = f" · local: `{loc}`"
            elif it.get("failure_reason"):
                tail = f" · *not downloaded ({it['failure_reason']})*"
            else:
                tail = " · *link only (not downloaded)*"
            lines.append(f"  [source]({it.get('url')}){tail}")
            if it.get("conflict"):
                det = (it.get("conflict_detail") or {}).get("abstract") or {}
                lines.append(
                    f"  > ⚠ **Metadata conflict** ({', '.join(it.get('conflict_fields') or [])}), "
                    f"similarity {det.get('similarity')} — used "
                    f"{(det.get('used') or {}).get('source')}, rejected "
                    f"{(det.get('rejected') or {}).get('source')}. Both variants are in `manifest.json`.")
            if it.get("status") == "pdf_unverified":
                lines.append(f"  > ⚠ **PDF unverified** — title match {it.get('title_match')}, "
                             f"below 0.70. Check the file before citing it.")
            abstract = (it.get("abstract") or "")[:220]
            if abstract:
                lines.append(f"  > {abstract}{'…' if len(it.get('abstract') or '') > 220 else ''}")
            lines.append("")
    (dest / "INDEX.md").write_text("\n".join(lines))
    print(f"wrote {dest / 'INDEX.md'} and {dest / 'manifest.json'} "
          f"({len(docs)} documents, {conflicts} conflicts, {link_only} link-only)")


def common_report(dest: Path) -> dict:
    f = dest / ".sdr" / "report.json"
    return json.loads(f.read_text()) if f.exists() else {}


if __name__ == "__main__":
    main()
